[package]
name = "better-auth"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
description = { workspace = true }
repository = { workspace = true }

[workspace]
members = [
    ".",
    "crates/better-auth-api",
    "crates/better-auth-core",
    "crates/better-auth-entity",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "The most comprehensive authentication framework for Rust"
repository = "https://github.com/better-auth-rs/better-auth-rs"

[workspace.dependencies]
# Asynchronous runtime
tokio = { version = "1.0", features = ["full"] }
tokio-util = "0.7"
async-trait = "0.1"
futures = "0.3"
# OpenAPI
utoipa = { version = "5", features = [
    "axum_extras",
    "uuid",
    "chrono",
    "time",
    "url",
    "preserve_path_order",
] }
# Database
sea-orm = { version = "1.1.16", features = [
    "runtime-tokio-rustls",
    "macros",
    "with-uuid",
    "with-chrono",
    "with-json",
    "with-ipnetwork",
] }
# Crypto provider
rustls = { version = "0.23", default-features = false, features = [
    "aws-lc-rs",
] }
# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# Configuration management
config = "0.15"
clap = { version = "4.5", features = ["derive", "env"] }
lazy_static = "1.4"
# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
# Error handling
anyhow = "1.0"
thiserror = "2.0"
backoff = "0.4"
# Time handling
chrono = { version = "0.4", features = ["serde"] }
# Data structures
uuid = { version = "1.18", features = ["v4", "v7", "serde"] }
# HTTP client
reqwest = { version = "0.12", features = ["json"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
incremental = false
debug = false

[profile.ci]
inherits = "release"
opt-level = 2
lto = "thin"
codegen-units = 16
